input()
S=input()
D,M=map(int,input().split())
a=sum(min(D*len(l),M+D)for l in S.translate(str.maketrans("HYU","   ")).split())
b=min(S.count(i)for i in"HYU")
print(a if a else"Nalmeok")
print(b if b else"I love HanYang University")