a, op1, b, op2, c = input().split()
p = eval(f"{a}{op1}{b}")
ans = eval(f"{p}{op2}{c}")

print("=================")
print("|SASA CALCULATOR|")
print(f"|{ans:15.3f}|")
print("-----------------")
print("|               |")
print("| AC         /  |")
print("| 7  8  9    *  |")
print("| 4  5  6    -  |")
print("| 1  2  3    +  |")
print("|    0  .    =  |")
print("=================")