print " ________"; "_"
print " \_     _"; "/"
print "   \   "; "/"
print "    | "; "|"
print "   /   "; "\"
print "  /     "; "\"
print " |       "; "|"
print "/---------"; "\"
print "| \-/ \-/ "; "|"
print "\---------"; "/"
print " \_______"; "/"