*q, c, u0, u1, u2 = map(int, input().split())
a, b = sorted(q)
l = ((a + min(b, a + c), a + min(b, a + c), 0), (b, c, a), (a + c, c, a))
ans = min(sum(s * t for s, t in zip(p, (1/u0, 1/u1, 1/u2))) for p in l)
print(ans)